### ISSUE TITLE
你好，看了你的论文，对融合结果的分析不是很理解，摄像头既然对目标没有跟踪上说明检测效果差，为什么还有检测框

### ISSUE THREAD

**Issue by muguangqingning** [vincentzhouwenqi/DWD_sensor_fusion#1]
![image](https://user-images.githubusercontent.com/88170435/171569665-0a3c5dc2-631f-4422-9194-37ff4af25536.png)

**Comment by VanniZhou** [comment]
是这样的，这一帧虽然没有跟踪上，没有跟踪框的输出，但是跟踪器并未被删除，本算法评价传感器是否退出是根据该传感器的所有跟踪器的指标来评判该传感器是否退出，如果退出整个传感器的检测结果均被删除，这一帧执行的时候三个传感器均未退出，融合结果采用的检测框进行融合，所以这一帧该目标仍有依赖于三种传感器的融合结果，只是该帧摄像头的融合权重较低。
